spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/orkut_clone
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
  flyway:
    enabled: true
    baseline-on-migrate: true
    out-of-order: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 12MB

server:
  port: 8080

app:
  storage:
    avatar-dir: ${AVATAR_STORAGE_DIR:uploads/avatars}
    public-base-url: ${AVATAR_PUBLIC_URL:/uploads/avatars}
    album-dir: ${ALBUM_STORAGE_DIR:uploads/albums}
    album-public-base-url: ${ALBUM_PUBLIC_URL:/uploads/albums}

jwt:
  secret: ${JWT_SECRET}
  expiration: 259200000
