spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/orkut_clone
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 12MB

server:
  port: 8080

app:
  storage:
    avatar-dir: ${AVATAR_STORAGE_DIR:uploads/avatars}
    public-base-url: ${AVATAR_PUBLIC_URL:/uploads/avatars}

jwt:
  secret: ${JWT_SECRET}
  expiration: 259200000
